version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    
phases:
  install:
    commands:
      - echo Entered the install phase...
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/

    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - ls && pwd && cd ../../../github.com/${owner}/${repo} && pwd && ls
      - echo Entered the build phase...
      - echo ${owner}
      - sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST -Dsonar.projectKey=$pkey -Dsonar.projectName=$pName
     
      
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase....
      - echo Build completed on `date`
artifacts:
  files:
    
    - appspec.yml
  discard-paths: yes
